services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mywebsite.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mywebsite.settings
      - key: PYTHON_VERSION
        value: 3.11
